package ladybugAdventures.enums;

public enum ErrorType {
	NONE_ERROR, FIELD_BORDER, MOVE_BLOCK, MOVE_HOLE, JUMP_BLOCK, JUMP_EMPTY_CELL, JUMP_OCCUPIED_CELL,
	JUMP_ON_HOLE, PUSH_EMPTY_CELL, PUSH_HOLE, PUSH_OCCUPIED_CELL, PUSH_TWO_BLOCKS, 
	PUSH_BLOCK_TO_OCCUPIED_CELL
}
